services:
  - type: web
    name: zoo-log
    env: python
    runtime: python-3.12.8
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: BASE_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: DEBUG_ERRORS
        value: "1"
      - key: BUILD
        value: "2026-03-21-01"
      - key: PYTHON_VERSION
        value: "3.12.8"
      - key: DB_DIR
        value: /data
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
